version: "3.9"

services:
  backend:
    build: .
    container_name: node-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - .:/app
    command: ["node", "dist/server.js"]
